[workspace]
members = ["channels", "example-block", "block-macros", "blocks"]

[package]
name = "block-flow"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
block_traits = { path = "block_traits" }
blocks = { path = "blocks" }
channels = { path = "channels" }
block-macros = { path = "block-macros" }

[dev-dependencies]