[workspace]
members = [
    "channels", 
    "example-block", 
    "block-macros", 
    "blocks", 
    "block-serialization",
    "execution-plan",
    "serialization",
    "serialization-macros",
    "weave",
    "trade-types",
    "intents",
]

[package]
name = "block-flow"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
block_traits = { path = "block_traits" }
block-macros = { path = "block-macros" }
execution-plan = { path = "execution-plan" }
block-serialization = { path = "block-serialization" }
blocks = { path = "blocks" }
channels = { path = "channels" }
intents = { path = "intents" }
serialization = { path = "serialization" }
serialization-macros = { path = "serialization-macros" }
trade_types = { path = "trade-types" }

[dev-dependencies]