[package]
name = "execution-plan"
version = "0.1.0"
edition = "2021"

[dependencies]
execution-context = { path = "../execution-context" }
block-traits = { path = "../block-traits" }
trade-types = { path = "../trade-types" }
weave = { path = "../weave" }
