[package]
name = "example-block"
version = "0.1.0"
edition = "2021"

[dependencies]
registry = { path = "../registry" }
block-macros = { path = "../block-macros" }
blocks = { path = "../blocks" }
block_traits = { path = "../block_traits" }

[dev-dependencies]